@Identity.API_HostAddress = https://localhost:7064


POST {{Identity.API_HostAddress}}/api/account/signup
Content-Type: application/json

{
  //SignUpQuery
}

###

POST {{Identity.API_HostAddress}}/api/account/testauth

###

POST {{Identity.API_HostAddress}}/api/account/login
Content-Type: application/json

{
  //LoginQuery
}

###
