apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-api
  template:
    metadata:
      labels:
        app: reviews-api
    spec:
      containers:
      - name: reviews-api
        image: dm8t34/reviews-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
