services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: strong_user
      RABBITMQ_DEFAULT_PASS: strong_password
    networks:
      - mynetwork

  identity.api:
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  products.api:
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  reviews.api:
    build:
      context: .
      dockerfile: Services/Reviews/Reviews.API/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  web.bff:
    build:
      context: .
      dockerfile: ApiGetaways/Web.BFF/Dockerfile
    depends_on:
      - reviews.api
      - products.api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge