services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal,1433;Database=mg_identity;User Id=dockeruser;Password=YourStrongPassword!;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "5051:80"
  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal,1433;Database=mg_products;User Id=dockeruser;Password=YourStrongPassword!;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "5052:80"