services:
  rabbitmq:
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal,1433;Database=mg_identity;User Id=dockeruser;Password=YourStrongPassword!;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "5051:80"

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal,1433;Database=mg_products;User Id=dockeruser;Password=YourStrongPassword!;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "5052:80"

  reviews.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal,1433;Database=mg_reviews;User Id=dockeruser;Password=YourStrongPassword!;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "5053:80"