services:
  identity.api:
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    networks:
      - mynetwork

  products.api:
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile
    networks:
      - mynetwork

  reviews.api:
    build:
      context: .
      dockerfile: Services/Reviews/Reviews.API/Dockerfile
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge